
apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp-deployment
  labels:
    app: webapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webapp
  template:
    metadata:
      labels:
        app: webapp
    spec:
      containers:
      - name: webapp
        image: 09440/py10:v2
        ports:
        - containerPort: 8000
        env:
        - name: SQL_USER
          valueFrom:
              secretKeyRef:
                name: postgres-secret
                key: postgres-user
        - name: SQL_PASSWORD
          valueFrom:
              secretKeyRef:
                name: postgres-secret
                key: postgres-password
        - name: SQL_DATABASE
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: postgres-db
        - name: SQL_HOST
          value: postgres-service
        - name: SQL_PORT
          value: "5432"
        - name: MEDIAFILES_HOST
          value: /home/marcel/repos/own/github/py10/public/mediafiles/
        - name: STATICFILES_HOST
          value: /home/marcel/repos/own/github/py10/public/staticfiles/
---
apiVersion: v1
kind: Service
metadata:
  name: webapp-service
spec:
  type: NodePort
  selector:
    app: webapp
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
      nodePort: 30100

